$(document).ready(function(){
    $("#DESIGN-img").click(function(){
        $("#DESIGN-img").fadeOut("slow").hide('1000')
        $("#DESIGNS").fadeIn("slow")
    });
    $("#DESIGNS").click(function(){
        $("#DESIGNS").fadeOut("slow")
        $("#DESIGN-img").fadeIn("slow")
    })
});